apiVersion: v1
kind: ConfigMap
metadata:
  name: &app-name go-cart-cm
  namespace: test-a
  labels:
    app: *app-name
data:
  VERSION: "1.0"
  ACCOUNT: "aws:992382474575"
  APP_NAME: "go-cart.arch-eks-002"
  PORT: "7001"
  ENV: "dev"

  DB_HOST: "rds-proxy-db-arch-02.proxy-cj4aqa08ettf.us-east-2.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  DB_MAX_CONNECTION: "10"
  CTX_TIMEOUT: "5"

  LOG_LEVEL: "warning" #info, error, warning
  OTEL_EXPORTER_OTLP_ENDPOINT: "arch-eks-002-otel-collector.default.svc.cluster.local:4317"

  OTEL_METRICS: "true"
  OTEL_STDOUT_TRACER: "false"
  OTEL_TRACES: "true"

  OTEL_LOGS: "false"
  OTEL_STDOUT_LOG_GROUP: "false"
  LOG_GROUP: "/mnt/c/Eliezer/log/go-cart.log"

  NAME_SERVICE_00: "go-inventory"
  URL_SERVICE_00: "https://go-inventory.architecture.caradhras.io"
  HOST_SERVICE_00: "go-inventory"
  CLIENT_HTTP_TIMEOUT_00: "5"